---
title: 'Technical Appendix "Women in STEM"'
date: today
author:
  - name: Jacob Hamel-Mottiez
    id: jc
    orcid: https://orcid.org/0009-0007-3666-908X
    email: jacob.hamel-Mottiez@mail.mcgill.ca
    affiliation: 
      - name: McGill University

code-links: 
  - icon: github
    text: Github
    href: https://github.com/JacobHamelMottiez

abstract: This file is the technical appendix for my article "Women in STEM". For any questions or issues, please email the author.

format: 
  html: default

code-fold: true 
code-summary: "Show Code"
number-sections: true
toc: true
toc-depth: 2
toc-location: left

theme:
  light: default
  dark: darkly


keywords:
  - Women 
  - STEM
  - Quebec

abstract-title: What is this file about?
---

```{r}
source("setup.R")

#| echo: false
# TODO: remove when first edition complete
status("wip")
```

# Packages
```{r}
#| warning: false
#| code-fold: false

library(gt)
library(here)
library(forcats)
library(plotly)
library(tidyverse)
library(readxl)
library(pubmedR)
library(dplyr)
library(gghighlight)
library(janitor)
```


```{r}
wis.data <- read_csv("C:/Users/jacob/OneDrive - Université Laval/Desktop/PROJECTS/Women_in_STEM/Data/theses-canada_2026-06-19.csv", skip = 2)
```


::: {.callout-warning}
## Incomplete dataset
It is weird, I only get 5000 results, when there should be 797 572. 
:::


```{r}
wis.data <- wis.data |> janitor::clean_names()
colnames(wis.data)

pub_year_uni <- wis.data |>
  group_by(universite, date_de_publication) |>
  summarise(n_publications = n(), .groups = "drop") 
```

```{r}
quebec_uni <- quebec_universities <- c(
  "Bishop's University",
  "Concordia University",
  "École de technologie supérieure",
  "École nationale d'administration publique",
  "HEC Montréal",
  "Institut national de la recherche scientifique",
  "McGill University",
  "Polytechnique Montréal",
  "Royal Military College Saint-Jean",
  "TÉLUQ University",
  "Université de Montréal",
  "Université de Sherbrooke",
  "Université Laval",
  "Université du Québec à Chicoutimi",
  "Université du Québec à Montréal",
  "Université du Québec à Rimouski",
  "Université du Québec à Trois-Rivières",
  "Université du Québec en Abitibi-Témiscamingue",
  "Université du Québec en Outaouais"
)
```

We have also access to other dataset, especially from Hughes et al. [Include reference]. 

```{r}
hughes.dion.data <- read.csv(
  r"(C:\Users\jacob\OneDrive - Université Laval\Desktop\PROJECTS\Women_in_STEM\Data\thesesMemoiresQC2000-2022-v20230508-1.csv)"
)
```

The following plot looks at the publication by universities, by year.
```{r}
hughes.dion.data <- hughes.dion.data  |> mutate(lang = ifelse(univ %in% c('McGill', 'Concordia'), "Anglophone", "Francophone"))

hughes.dion.data <- hughes.dion.data  |> mutate(UQ = ifelse(univ %in% c('UQAM', 'UQO', 'UQAR', 'UQAT', 'UQTR', 'UQAC'), "UQ", "-UQ"))

univ.year <- hughes.dion.data |> select(univ, année, lang, UQ)
univ.year <- univ.year |> group_by(univ, année) |>  mutate(n = sum(année)) |> unique()

ggplot(univ.year, aes(x = année, y = n, group = univ, color = univ)) +
  geom_smooth() + 
  facet_wrap(facets = 'UQ')
```

Here, we look at the sum of all MA's and Phd's thesis by university. 
```{r}
univ.total = hughes.dion.data |> select(univ, lang, UQ) |> group_by(univ) |> mutate(n = n()) |> unique()


plot1 <- ggplot(univ.total, aes(x = reorder(univ, n), y = n, color = lang, fill = lang)) +
  geom_col(show.legend = FALSE) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot1
```


```{r}
ggplotly(plot1)
```